version: "{build}"

image:
- Visual Studio 2019

configuration:
- Debug
- Release

platform:
- 32
- 64

build:
  project: projects\visual-studio\ffsm-16-vs.sln
  parallel: true
  verbosity: minimal

test_script:
- cmd: binaries-%PLATFORM%\ffsm-16-%CONFIGURATION%-%PLATFORM%.exe
